//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_CityFlora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kauf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kauf()
        {
            this.Pflanzens = new HashSet<Pflanzen>();
        }
    
        public int K_ID { get; set; }
        public string K_Shop { get; set; }
        public Nullable<System.DateTime> K_Datum { get; set; }
        public Nullable<decimal> K_Preis { get; set; }
        public Nullable<int> K_P_ID { get; set; }
    
        public virtual Pflanzen Pflanzen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pflanzen> Pflanzens { get; set; }
    }
}
