//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_CityFlora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Steckbrief
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Steckbrief()
        {
            this.Pflanzens = new HashSet<Pflanzen>();
        }
    
        public int ST_ID { get; set; }
        public string ST_Name { get; set; }
        public string ST_Art { get; set; }
        public string ST_GuteNachbar { get; set; }
        public Nullable<decimal> ST_Hoehe { get; set; }
        public Nullable<decimal> ST_Wurzeltiefe { get; set; }
        public byte[] ST_Bild { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pflanzen> Pflanzens { get; set; }
    }
}
