//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityFLORA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pflanzen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pflanzen()
        {
            this.Kaufs = new HashSet<Kauf>();
            this.Schaedlings = new HashSet<Schaedling>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public Nullable<System.DateTime> P_Gepflanzt { get; set; }
        public Nullable<int> P_Kauf { get; set; }
        public string P_Topf { get; set; }
        public Nullable<int> P_Standort { get; set; }
        public Nullable<int> P_Steckbrief { get; set; }
        public Nullable<System.DateTime> P_Bluet_Von { get; set; }
        public Nullable<System.DateTime> P_Bluet_Bis { get; set; }
        public string P_Notiz { get; set; }
        public Nullable<int> P_Schaedling { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kauf> Kaufs { get; set; }
        public virtual Kauf Kauf { get; set; }
        public virtual Schaedling Schaedling { get; set; }
        public virtual Standort Standort { get; set; }
        public virtual Steckbrief Steckbrief { get; set; }
        public virtual Topf Topf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schaedling> Schaedlings { get; set; }
    }
}
